@startuml
class ConjuntoPersistente {
    agregar()
    eliminar()
    contiene()
    union()
    interseccion()
    diferencia()
    guardar()
    mostrar()
        filename
    elementos
    elementos
    __init__()
}
@enduml